# 배포 환경 설정
spring:
  application:
    name: manchui

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # 이미지 크기 제한
  servlet:
    multipart:
      maxFileSize: ${MAX_FILE_SIZE}
      maxRequestSize: ${MAX_REQUEST_SIZE}
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    defer-datasource-initialization: true

  jwt:
    secret: ${JWT_SECRET_KEY}

kakao:
  client:
    id: ${KAKAO_CLIENT_ID}
    secret: ${KAKAO_CLIENT_SECRET}
    redirect-uri: https://manchui.shop/login/oauth2/callback/kakao
  urls:
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me

google:
  client:
    id: ${GOOGLE_CLIENT_ID}
    secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: https://manchui.shop/login/oauth2/callback/google
  urls:
    token-uri: https://oauth2.googleapis.com/token
    user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo

naver:
  client:
    id: ${NAVER_CLIENT_ID}
    secret: ${NAVER_CLIENT_SECRET}
    redirect-uri: https://manchui.shop/login/oauth2/callback/naver
  urls:
    token-uri: https://nid.naver.com/oauth2.0/token
    user-info-uri: https://openapi.naver.com/v1/nid/me

token:
  access:
    expiration: ${ACCESS_TOKEN_EXPIRATION}
  refresh:
    expiration: ${REFRESH_TOKEN_EXPIRATION}

cloud:
  aws:
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

gathering:
  date-pattern: "yyyy-MM-dd HH:mm:ss"
  due-date-hours-before: 5